import { router } from "expo-router";
import { ScrollView, StyleSheet, Text, View, Pressable } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useBibleNoteStore } from "@/lib/bible-note-store";
import { featureReadiness, getReadinessLabel, normalizeFeatureReadiness } from "@/lib/feature-readiness";

export default function CapabilitiesScreen() {
  const colors = useColors();
  const { sermons, streak } = useBibleNoteStore();
  const noteCount = sermons.reduce((total, sermon) => total + sermon.notes.length, 0);
  const openActionCount = sermons.reduce((total, sermon) => total + sermon.actionItems.filter((item) => !item.completed).length, 0);
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="px-5 pt-3"><Pressable accessibilityRole="button" accessibilityLabel="Back to profile" accessibilityHint="Returns to your local practice settings." onPress={() => router.back()}><Text style={[styles.back, { color: colors.primary }]}>‹  Back to profile</Text></Pressable><Text style={[styles.eyebrow, { color: colors.muted }]}>CAPABILITY CENTER</Text><Text style={[styles.title, { color: colors.foreground }]}>What’s ready for you</Text><Text style={[styles.subtitle, { color: colors.muted }]}>{sermons.length > 0 ? `${sermons.length} sermon${sermons.length === 1 ? "" : "s"}, ${noteCount} note${noteCount === 1 ? "" : "s"}, and ${openActionCount} open action${openActionCount === 1 ? "" : "s"} are saved locally. This view shows which parts of your current practice are ready.` : `Your local journal is ready to begin. This view shows which parts of the current practice are available without an account.`}</Text><ScrollView contentContainerStyle={styles.list}>{normalizeFeatureReadiness(featureReadiness).map((feature) => { const available = feature.readiness === "available"; const tone = available ? colors.success : feature.readiness === "backend_required" ? colors.warning : colors.primary; return <View key={feature.key} style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.cardHeader}><Text style={[styles.cardTitle, { color: colors.foreground }]}>{feature.title}</Text><View style={[styles.badge, { backgroundColor: tone }]}><Text style={styles.badgeText}>{getReadinessLabel(feature.readiness)}</Text></View></View><Text style={[styles.description, { color: colors.muted }]}>{feature.description}</Text></View>; })}<Text style={[styles.note, { color: colors.muted }]}>{streak > 0 ? `Your current rhythm is ${streak} day${streak === 1 ? "" : "s"}. Local notes, action items, and Prayer Lock progress remain available on this device.` : "Local notes, action items, and Prayer Lock progress remain available on this device."}</Text></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ back: { fontSize: 16, fontWeight: "700", marginBottom: 24 }, eyebrow: { fontSize: 11, letterSpacing: 1.5, fontWeight: "800" }, title: { fontSize: 30, lineHeight: 37, fontWeight: "700", marginTop: 5 }, subtitle: { fontSize: 15, lineHeight: 22, marginTop: 10, marginBottom: 20 }, list: { gap: 12, paddingBottom: 24 }, card: { borderWidth: 1, borderRadius: 18, padding: 16, gap: 10 }, cardHeader: { gap: 10 }, cardTitle: { fontSize: 17, fontWeight: "700" }, badge: { alignSelf: "flex-start", borderRadius: 999, paddingHorizontal: 9, paddingVertical: 5 }, badgeText: { color: "#FFFDF8", fontSize: 11, fontWeight: "800" }, description: { fontSize: 14, lineHeight: 21 }, note: { fontSize: 12, lineHeight: 18, textAlign: "center", paddingHorizontal: 10 } });
